[project]
name = "pyroh"
description = "A friendly, asyncio-like Python wrapper for Iroh"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
  "Programming Language :: Rust",
]
dynamic = ["version"]

[dependency-groups]
dev = ["maturin"]

[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module", "pyo3/abi3-py314"]
module-name = "pyroh._iroh"
python-source = "."  # ./pyroh
